personal:
  email: "me@jedevc.com"
  location: ["Birmingham", "UK"]
  name: "Justin Chadwell"
  phone: ""
  content: "Building next-gen dev tooling to ship fast *and* right ⚒️"
  website: "https://jedevc.com"
  socials:
    github: jedevc
    linkedin: jedevc

styles:
  highlight: "#ffd832"

sections:
  - name: Work
    entries:
      - title: "Dagger"
        subtitle: "Software Engineer"
        startDate: "2023-09-05"
        endDate: ""
        website: https://dagger.io
        content: |
          - Worked in the core team to deliver major new [Dagger engine](https://github.com/dagger/dagger)
            features and performance improvements, providing subject-matter
            expertise for better native Git support, improved caching, and
            integrations with docker/containerd, with over 700 authored + 1000
            reviewed pull-requests touching almost every codebase component.
          - Defined and led the release process and cadence for each
            fortnightly release (personally cutting over 20), establishing
            standards for milestones, communication, and backwards-compatibility
            guarantees.
          - Co-led a massive migration to a custom graph evaluator, integrating
            a legacy DAG-based cache system with a new GraphQL-based cache,
            improving scalability and maintainability.
          - Improved automation in our own internal CI, with a focus on 
            low-touch releases, bringing release preparation times down from an
            entire day to half an hour.
          - Handled escalation of feature requests and resolution of complex
            production issues for high-priority users and customers.
          - Mentored and upskilled junior engineers through structured
            onboarding, technical guidance, and pair-programming.
          - Assisted with booth duty across three KubeCon US/EU events,
            pitching, discussing, and demoing Dagger to attendees.

      - title: "Docker"
        subtitle: "Software Engineer"
        startDate: "2022-04-05"
        endDate: "2023-09-08"
        website: https://docker.com
        content: |
          - Supported the open-source container ecosystem by developing and
            maintaining popular open-source projects, [Buildx](https://github.com/docker/buildx)
            and [BuildKit](https://github.com/moby/buildkit) to power the
            `docker build` experience.
          - Improved software supply chain security by integrating in-toto
            attestations and SBOMs into BuildKit.
          - Prototyped and helped launch the Docker Build Cloud service for
            remote BuildKit-powered compute.

      - title: "Pexip"
        subtitle: "Software Engineer"
        startDate: "2021-09-01"
        endDate: "2022-03-25"
        website: https://pexip.com
        content: |
          - Maintained internal build systems, CI/CD infrastructure and
            developer tooling to enable enhanced developer productivity.
          - Designed internal fuzzing and static analysis pipelines to automate
            bug hunting and increase the visibility of security issues.
          - Investigated complex low-level video codec issues from production
            environments.

      - title: "Progressive Access"
        subtitle: "Software Engineer"
        startDate: "2019-11-01"
        endDate: "2022-01-01"
        website: https://progressiveaccess.com
        content: |
          - Created and managed frontend, authentication, payment, and mailing
            microservices for the Live Chemistry SaaS platform.
          - Wrote CI/CD pipelines utilizing Terraform and Docker to automate
            deployment.
          - Designed and developed a new Jamstack home site and blog to be the
            public face of the company.

      - title: "ARM"
        subtitle: "Software Intern"
        startDate: "2019-06-01"
        endDate: "2019-09-01"
        website: https://www.arm.com/
        content: |
          - Introduced support for next-generation ARM security features in open-source
            firmware.

  - name: Education
    entries:
      - title: "Computer Science BSc"
        subtitle: "University of Birmingham"
        startDate: "2018-09-01"
        endDate: "2021-07-01"
        content: |
          Bachelor of Science with First Class Honours.

  - name: Skills
    minimal: true
    entries:
      - title: "Systems"
        keywords:
          - "Go"
          - "C/C++"
          - "Rust"
          - "Linux"
      - title: "Platform"
        keywords:
          - "Docker"
          - "Containerd"
          - "Kubernetes"
          - "GitHub Actions"
          - "GitLab CI"
      - title: "Scripting"
        keywords:
          - "Python"
          - "Bash"
          - "Docker"
      - title: "Frontend"
        keywords:
          - "HTML"
          - "CSS"
          - "Javascript"
          - "React"
      - title: "Security"
        keywords:
          - "Fuzzing"
          - "Reverse engineering"
          - "Static analysis"
          - "Vulnerability scanning"

  # - name: Achievements
  #   boxes:
  #     - title: "Top Marks in BSc Computer Science"
  #       subtitle: "University of Birmingham"
  #       endDate: "2021-07-15"
  #       content: |
  #         I scored the highest total mark in my graduating cohort for BSc Computer
  #         Science in 2021.
  #     - title: "CSS and AFNOM Member of the Year"
  #       subtitle: "University of Birmingham"
  #       endDate: "2021-07-22"
  #       content: |
  #         I was member of the year for both [CSS](https://cssbham.com) and
  #         [AFNOM](https://afnom.net), which I've been an active part of since my
  #         first year.
  #     - title: "Great Achievement in EPS (shortlisted)"
  #       subtitle: "University of Birmingham"
  #       endDate: "2021-07-22"
  #       content: |
  #         I was recognized for my contributions to the EPS college for my
  #         volunteering work.

  - name: Interests
    entries:
      - title: "Food"
        content: |
          I love all things food, whether that's trying tasting menus
          travelling around the UK, hosting friends and family, or even just
          adding to my cookbook collection!
      - title: "Gaming"
        content: |
          I play quite a lot of games, from board and card games with a group
          of friends, all the way to single-player games on my computer at home (I
          do love a good roguelike).
      - title: "Tech"
        content: |
          I enjoy tinkering with a number of technical projects at home whenever I
          have a few spare moments (few and far between though they may be!)
