personal:
  email: "me@jedevc.com"
  location: ["Birmingham", "UK"]
  name: "Justin Chadwell"
  phone: ""
  content: "Software Engineer working on awesome open-source projects 🎉"
  website: "https://jedevc.com"

styles:
  highlight: "#ffd832"

sections:
  - name: Work
    entries:
      - title: "Docker"
        subtitle: "Software Engineer"
        startDate: "2022-04-05"
        endDate: "2023-09-08"
        website: https://docker.com
        content: |
          - Supporting the open-source ecosystem by developing and maintaining
            popular open-source projects, [Buildx](https://github.com/docker/buildx)
            and [BuildKit](https://github.com/moby/buildkit).
          - Improving software supply chain security by integrating in-toto
            attestations and SBOMs into BuildKit.
      - title: "Pexip"
        subtitle: "Software Engineer"
        startDate: "2021-09-01"
        endDate: "2022-03-25"
        website: https://pexip.com
        content: |
          - Designed internal fuzzing and static analysis pipelines to automate
            bug hunting and increase visibility of security issues.
          - Maintained build systems, CI/CD infrastructure and developer tooling
            to enable developer productivity and communication across teams.
          - Investigated complex low-level video codec issues from production
            environments.
          - Assisted in hiring processes by reviewing homeworks and interviewing
            candidates.
      - title: "Progressive Access"
        subtitle: "Software Engineer"
        startDate: "2019-11-01"
        endDate: "2022-01-01"
        website: https://progressiveaccess.com
        content: |
          - Designed and developed a new Jamstack home site and blog from scratch.
          - Created a frontend as well as authentication, payment and mailing
            microservices for the Live Chemistry SaaS platform.
          - Wrote CI/CD pipelines utilizing Terraform and Docker to automate
            deployment.
      - title: "ARM"
        subtitle: "Software Intern"
        startDate: "2019-06-01"
        endDate: "2019-09-01"
        website: https://www.arm.com/
        content: |
          - Introduced support for next-gen ARM security features in open-source
            firmware.
          - Presented to engineers in the Open Source Software Group about using the
            Undefined Behavior Sanitizer in firmware, an area I researched while
            interning.

  - name: Education
    entries:
      - title: "Computer Science BSc"
        subtitle: "University of Birmingham"
        startDate: "2018-09-01"
        endDate: "2021-07-01"
        content: |
          - [**97%**] Advanced Networking
          - [**96%**] Algorithms and Complexity
          - [**95%**] Programming Languages
          - [**94%**] Security of Real-World Systems
          - [**86%**] Final Year Project
      - title: "A Levels"
        subtitle: "KISC"
        startDate: "2017-08-01"
        endDate: "2018-06-01"
        content: |
          - [**A\***] Computer Science
          - [**A\***] Mathematics
          - [**A**] English Language

  - name: Projects
    entries:
      - title: "Hack The Midlands CTF"
        website: "https://github.com/jedevc/HackTheMidlandsCTF20"
        keywords:
          - "Hacking"
          - "Linux"
        content: |
          Capture the Flag competition for [Hack The Midlands](https://hackthemidlands.com/)
          4.0 and 5.0.

          I developed a CTF mini-event over both years, involving chatbots, DNS
          servers, hackable games, providing an introduction to computer security
          for attendees.
      - title: "AppArea"
        website: "https://github.com/jedevc/apparea"
        keywords:
          - "Go"
          - "Linux"
        content: |
          An entirely open-source port forwarding helper from localhost built using
          SSH tunnels.

          I built it out of a frustration that none of the existing tools in the area were
          open source or had minimal client-side dependencies.

  - name: Skills
    minimal: true
    entries:
      - title: "Systems"
        keywords:
          - "C/C++"
          - "Go"
          - "Rust"
          - "Linux"
      - title: "Scripting"
        keywords:
          - "Python"
          - "Bash"
          - "Docker"
      - title: "Frontend"
        keywords:
          - "HTML/CSS"
          - "Javascript"
          - "React"
      - title: "Security"
        keywords:
          - "Fuzzing"
          - "Reverse engineering"
          - "Static analysis"

  - name: Volunteering
    entries:
      - title: "HackTheMidlands"
        subtitle: "Organizer"
        website: "http://hackthemidlands.com/"
        startDate: "2019-06-01"
        endDate: ""
        content: |
          - Helped plan and organize a hackathon of over 250 attendees.
          - Developed a [custom virtual badge system](https://github.com/jedevc/HackTheMidlandsBadges22)
            to allow users to customize their badges using Lua.
          - Designed and ran a security-focused CTF, accessible to attendees of
            all ages and skill levels.
      - title: "AFNOM"
        subtitle: "Co-lead"
        website: "http://afnom.net/"
        startDate: "2018-10-01"
        endDate: "2021-07-01"
        content: |
          - Represented the university in CTFs as a top 10 ranked UK team.
          - Developed WhatTheCTF competitions for UoB's School of Computer
            Science and [INRIA's 2019 SILM summer school](https://silm-school.inria.fr/ctf/).
          - Managed infrastructure on Google Cloud Platform and Hetzner using
            Docker and Kubernetes.
      - title: "Computer Science Society"
        subtitle: "Vice President"
        website: "http://cssbham.com/"
        startDate: "2019-03-01"
        endDate: "2020-06-01"
        content: |
          - Built up the CompSci community at UoB by encouraging participation in
            society events, and enhancing relations with societies at other
            Universities.
          - Organized and ran a number of events, including hackathons, talks and
            workshops.
          - Re-designed the society's website to engage students and provide
            a hub for important information and news.
          - Became a Google Student Developer Club Lead to include more workshops
            and talks.

  - name: Achievements
    boxes:
      - title: "Top Marks in BSc Computer Science"
        subtitle: "University of Birmingham"
        endDate: "2021-07-15"
        content: |
          I scored the highest total mark in my graduating cohort for BSc Computer
          Science in 2021.
      - title: "CSS and AFNOM Member of the Year"
        subtitle: "University of Birmingham"
        endDate: "2021-07-22"
        content: |
          I was member of the year for both [CSS](https://cssbham.com) and
          [AFNOM](https://afnom.net), which I've been an active part of since my
          first year.
      - title: "Great Achievement in EPS (shortlisted)"
        subtitle: "University of Birmingham"
        endDate: "2021-07-22"
        content: |
          I was recognized for my contributions to the EPS college for my
          volunteering work.

  - name: Interests
    entries:
      - title: "Tech"
        content: |
          I enjoy tinkering with a number of technical projects at home whenever I
          have a few spare moments. I'm also attempting to branch into blogging
          more regularly, producing technical content and tutorials for both
          beginners and experienced developers.
      - title: "Gaming"
        content: |
          I love playing games, from a variety of board and card games with a group
          of friends, all the way to single-player games on my computer at home (I
          do love a good roguelike).
      - title: "Food"
        content: |
          I'm always up for trying new food, and regularly try and find new places
          to eat out wherever I am. I also really enjoy cooking at home for fun!
